version: '3.1'
services:
  api:
    image: mariavmasmas
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file:
      - .env
    networks:
      - "orionapp"
    volumes:
      - ./app:/app/app
    ports:
      - "5003:8080"


networks:
  orionapp: